GO=$(shell which go)

.PHONY: deps test lint install
.DEFAULT_GOAL := install

deps:
	@$(GO) get github.com/golangci/golangci-lint/cmd/golangci-lint
	@$(GO) get ./...

lint:
	@echo gofmt...
	@if [ ! -z "$(shell gofmt -s -l .)" ]; then echo "gofmt blames these files:" && gofmt -s -l . && exit 1; fi
	@echo go vet...
	@$(GO) vet ./...
	@echo golangci-lint...
	@golangci-lint run --tests=false --enable-all -D prealloc -D gochecknoglobals ./...
	@echo test go install...
	@test -z $(shell $(GO) install)

test:
	@$(GO) test -v -race ./...

install:
	@$(GO) install
