GO=$(shell which go)

.PHONY: deps test lint install
.DEFAULT_GOAL := install

deps:
	@$(GO) get github.com/golang/lint/golint
	@$(GO) get honnef.co/go/tools/cmd/megacheck
	@$(GO) get ./...

lint:
	@echo gofmt...
	@if [ ! -z "$(shell gofmt -s -l .)" ]; then echo "gofmt blames these files:" && gofmt -s -l . && exit 1; fi
	@echo go vet...
	@$(GO) vet ./...
	@echo megacheck...
	@megacheck ./...
	@echo golint...
	@golint -set_exit_status ./...
	@echo test go install...
	@test -z $(shell $(GO) install)

test:
	@$(GO) test -v ./...

install:
	@$(GO) install
